app/account/urls.py
from django.urls import path

from account.views import (
    UserSignUpView,
    UserActivateView,
    ProfileView
)

app_name = 'account'


urlpatterns = [
    path('signup/', UserSignUpView.as_view(), name='signup'),
    path('activate/<uuid:username>/', UserActivateView.as_view(), name='activate'),
    path('profile/', ProfileView.as_view(), name='profile')
]

app/currency/api/urls.py
from rest_framework.routers import DefaultRouter

from currency.api.views import RateViewSet, SourceViewSet, ContactUsViewSet

# from currency.api.views import RateApiView, RateDetailApiView

app_name = 'api-currency'

router = DefaultRouter()
router.register(r'rates', RateViewSet, basename='rates')
router.register(r'sources', SourceViewSet, basename='sources')
router.register(r'contact-us', ContactUsViewSet, basename='contact-us')

urlpatterns = [
    # path('rates/', RateApiView.as_view(), name='rates-list'),
    # path('rates/<int:pk>/', RateDetailApiView.as_view(), name='rates-details')
]

urlpatterns += router.urls

app/currency/urls.py
from django.urls import path

from currency.views import (
    RatesListView,
    RateCreateView,
    RateDetailView,
    RateUpdateView,
    RateDeleteView,
    MessagesListView,
    MessageCreateView,
    MessageUpdateView,
    MessageDeleteView,
    MessageDetailView,
    SourcesListView,
    SourceCreateView,
    SourceUpdateView,
    SourceDeleteView,
    SourceDetailView
)

app_name = 'currency'


urlpatterns = [
    path('rate/list/', RatesListView.as_view(), name='rate-list'),
    path('rate/create/', RateCreateView.as_view(), name='rate-create'),
    path('rate/update/<int:pk>/', RateUpdateView.as_view(), name='rate-update'),
    path('rate/delete/<int:pk>/', RateDeleteView.as_view(), name='rate-delete'),
    path('rate/details/<int:pk>/', RateDetailView.as_view(), name='rate-details'),

    path('message/list/', MessagesListView.as_view(), name='message-list'),
    path('message/create/', MessageCreateView.as_view(), name='message-create'),
    path('message/update/<int:pk>/', MessageUpdateView.as_view(), name='message-update'),
    path('message/delete/<int:pk>/', MessageDeleteView.as_view(), name='message-delete'),
    path('message/details/<int:pk>/', MessageDetailView.as_view(), name='message-details'),

    path('source/list/', SourcesListView.as_view(), name='source-list'),
    path('source/create/', SourceCreateView.as_view(), name='source-create'),
    path('source/update/<int:pk>/', SourceUpdateView.as_view(), name='source-update'),
    path('source/delete/<int:pk>/', SourceDeleteView.as_view(), name='source-delete'),
    path('source/details/<int:pk>/', SourceDetailView.as_view(), name='source-details')
]

app/settings/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from django.contrib.auth.urls import views
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

...

schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path('admin/', admin.site.urls),

    path('auth/', include('django.contrib.auth.urls')),
    path('account/', include('account.urls')),

    path('password_change/', views.PasswordChangeView.as_view(), name='password_change.html'),
    path('password_change/done/', views.PasswordChangeView.as_view(), name='password_change_done.html'),
    path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('__debug__/', include('debug_toolbar.urls')),

    path('', TemplateView.as_view(template_name='index.html'), name='index'),

    path('currency/', include('currency.urls')),
    path('api/currency/', include('currency.api.urls')),

    path('api/', include('account.api.urls')),

    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/currency/models.py
from django.db import models
from django.templatetags.static import static

from currency.choices import RateCurrencyChoices


def source_path(instance, filename):
    return f"sources/{instance.name}/{filename}"


class Rate(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    currency = models.PositiveSmallIntegerField(
        choices=RateCurrencyChoices.choices,
        default=RateCurrencyChoices.USD
    )
    buy = models.DecimalField(max_digits=6, decimal_places=2)
    sale = models.DecimalField(max_digits=6, decimal_places=2)
    source = models.ForeignKey('currency.Source', on_delete=models.CASCADE)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'Currency: {self.get_currency_display()}'


class ContactUs(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=128)
    email_from = models.EmailField()
    subject = models.CharField(max_length=50)
    message = models.CharField(max_length=255)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'Email from: {self.email_from}'


class Source(models.Model):
    source_url = models.CharField(max_length=255)
    name = models.CharField(max_length=64)
    note = models.CharField(max_length=255, null=True, blank=True)
    code_name = models.CharField(max_length=64, unique=True)
    source_logo = models.FileField(
        default=None,
        null=True,
        blank=True,
        upload_to=source_path
    )

    def __str__(self):
        return self.name

    @property
    def source_logo_url(self):
        if self.source_logo:
            return self.source_logo.url

        return static('no-image.png')


class RequestResponseLog(models.Model):
    path = models.CharField(max_length=255)
    request_method = models.CharField(max_length=10)
    time = models.DecimalField(max_digits=30, decimal_places=20)

app/currency/forms.py
from django import forms

from currency.models import Rate, ContactUs, Source


class RateForm(forms.ModelForm):
    class Meta:
        model = Rate
        fields = (
            'buy',
            'sale',
            'source',
            'currency'
        )


class ContactUsForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = (
            'name',
            'email_from',
            'subject',
            'message'
        )


class SourceForm(forms.ModelForm):
    class Meta:
        model = Source
        fields = (
            'source_url',
            'name',
            'note',
            'source_logo'
        )

app/currency/api/views.py
from django_filters import rest_framework as filters
from django.core.cache import cache

from rest_framework import viewsets
from rest_framework.decorators import action
from rest_framework.response import Response
# from rest_framework import generics
from rest_framework.permissions import AllowAny
from rest_framework import filters as rest_framework_filters

from currency import constants
from currency.filters import RateFilter, ContactUsFilter
from currency.api.serializers import RateSerializer, SourceSerializer, ContactUsSerializer
from currency.choices import RateCurrencyChoices
from currency.models import Rate, Source, ContactUs
from currency.paginators import RatesPagination, ContactUsPagination
from currency.throttlers import AnonCurrencyThrottle


# class RateApiView(generics.ListCreateAPIView):
#     queryset = Rate.objects.all().select_related('source')
#     serializer_class = RateSerializer  # json.dumps, json.loads
#
#
# class RateDetailApiView(generics.RetrieveUpdateDestroyAPIView):
#     queryset = Rate.objects.all()
#     serializer_class = RateSerializer

class RateViewSet(viewsets.ModelViewSet):
    queryset = Rate.objects.all()
    serializer_class = RateSerializer
    pagination_class = RatesPagination
    permission_classes = (AllowAny,)
    filter_backends = (
        filters.DjangoFilterBackend,
        rest_framework_filters.OrderingFilter,
    )
    filterset_class = RateFilter
    ordering_fields = ('id', 'created', 'buy', 'sale')
    throttle_classes = (AnonCurrencyThrottle,)

    @action(detail=False, methods=('GET',))
    def latest(self, request, *args, **kwargs):
        latest_rates = []

        cached_rates = cache.get(constants.LATEST_RATE_CACHE)
        if cached_rates:
            return Response(cached_rates)

        for source_obj in Source.objects.all():
            for currency in RateCurrencyChoices:
                latest = Rate.objects.filter(
                    source=source_obj,
                    currency=currency) \
                    .order_by('-created') \
                    .first()

                if latest:
                    latest_rates.append(RateSerializer(instance=latest).data)

        cache.set(constants.LATEST_RATE_CACHE, latest_rates, 60 * 60 * 24 * 7)

        return Response(latest_rates)


class SourceViewSet(viewsets.ModelViewSet):
    queryset = Source.objects.all()
    serializer_class = SourceSerializer
    permission_classes = (AllowAny,)


class ContactUsViewSet(viewsets.ModelViewSet):
    queryset = ContactUs.objects.all()
    serializer_class = ContactUsSerializer
    pagination_class = ContactUsPagination
    permission_classes = (AllowAny,)
    filter_backends = (
        filters.DjangoFilterBackend,
        rest_framework_filters.OrderingFilter,
        rest_framework_filters.SearchFilter,
    )
    filterset_class = ContactUsFilter
    ordering_fields = ('id', 'created', 'name', 'email_from', 'subject')
    search_fields = ['name', 'email_from']

app/currency/views.py
from django_filters.views import FilterView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView

from currency.filters import RateFilter, ContactUsFilter, SourceFilter
from currency.models import Rate, ContactUs, Source
from currency.forms import RateForm, ContactUsForm, SourceForm


class RatesListView(FilterView):
    queryset = Rate.objects.all().select_related('source')
    template_name = 'list_rates.html'
    paginate_by = 7
    filterset_class = RateFilter

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter_pagination'] = '&'.join(
            f'{key}={value}' for key, value in self.request.GET.items() if key != 'page'
        )
        return context


class RateDetailView(LoginRequiredMixin, DetailView):
    queryset = Rate.objects.all()
    template_name = 'rate_details.html'


class RateCreateView(CreateView):
    form_class = RateForm
    template_name = 'rate_create.html'
    success_url = reverse_lazy('currency:rate-list')


class RateUpdateView(UserPassesTestMixin, UpdateView):
    def test_func(self):
        return self.request.user.is_superuser

    form_class = RateForm
    template_name = 'rate_update.html'
    success_url = reverse_lazy('currency:rate-list')
    queryset = Rate.objects.all()


class RateDeleteView(UserPassesTestMixin, DeleteView):
    def test_func(self):
        if self.request.user.is_superuser:
            return True

    queryset = Rate.objects.all()
    template_name = 'rate_delete.html'
    success_url = reverse_lazy('currency:rate-list')


class MessagesListView(FilterView):
    queryset = ContactUs.objects.all()
    template_name = 'list_message.html'
    paginate_by = 10
    filterset_class = ContactUsFilter

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter_pagination'] = '&'.join(
            f'{key}={value}' for key, value in self.request.GET.items() if key != 'page'
        )
        return context


class MessageDetailView(DetailView):
    queryset = ContactUs.objects.all()
    template_name = 'message_details.html'


class MessageCreateView(CreateView):
    form_class = ContactUsForm
    template_name = 'message_create.html'
    success_url = reverse_lazy('currency:message-list')

    def _send_mail(self):
        subject = 'User Contact Us'
        # recipient = settings.DEFAULT_FROM_EMAIL
        message = f'''
            Request from: {self.object.name}
            Reply to email: {self.object.email_from}
            Subject: {self.object.subject}
            Body: {self.object.message}
        '''
        from currency.tasks import send_mail
        '''
        0 - 8.59 | 9.00 - 19.00 | 19.01 23.59
           9.00  |    send      | 9.00 next day
        '''
        # from datetime import datetime
        send_mail.apply_async(
            kwargs={'subject': subject, 'message': message},
            # countdown=20
            # eta=datetime(2023, 4, 4, 00, 38, 0)
        )

    def form_valid(self, form):
        redirect = super().form_valid(form)
        self._send_mail()
        return redirect


class MessageUpdateView(UpdateView):
    form_class = ContactUsForm
    template_name = 'message_update.html'
    success_url = reverse_lazy('currency:message-list')
    queryset = ContactUs.objects.all()


class MessageDeleteView(DeleteView):
    queryset = ContactUs.objects.all()
    template_name = 'message_delete.html'
    success_url = reverse_lazy('currency:message-list')


class SourcesListView(FilterView):
    template_name = 'list_sources.html'
    queryset = Source.objects.all()
    paginate_by = 7
    filterset_class = SourceFilter

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter_pagination'] = '&'.join(
            f'{key}={value}' for key, value in self.request.GET.items() if key != 'page'
        )
        return context


class SourceDetailView(DetailView):
    queryset = Source.objects.all()
    template_name = 'source_details.html'


class SourceCreateView(CreateView):
    form_class = SourceForm
    template_name = 'source_create.html'
    success_url = reverse_lazy('currency:source-list')


class SourceUpdateView(UpdateView):
    form_class = SourceForm
    template_name = 'source_update.html'
    success_url = reverse_lazy('currency:source-list')
    queryset = Source.objects.all()


class SourceDeleteView(DeleteView):
    queryset = Source.objects.all()
    template_name = 'source_delete.html'
    success_url = reverse_lazy('currency:source-list')

app/currency/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
          integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N"
          crossorigin="anonymous">

    <title>Currency - {% block title %}{% endblock title%}</title>
</head>
<body>

{% include 'includes/navbar.html' %}

<div class="container">
{% block content %}
{% endblock content %}
</div>

<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF"
        crossorigin="anonymous"></script>

<div class="container fixed-bottom">
{% include 'includes/footer.html' %}
</div>
</body>
</html>

app/currency/templates/index.html
{% extends 'base.html' %}

{% block title %}
    Index
{% endblock title %}

{% block content %}

>> Index Page <<

{% endblock content %}

app/currency/templates/list_rates.html
{% extends 'base.html' %}

{% block title %}
    Rates
{% endblock title %}

{% block content %}

<a href="{% url 'currency:rate-create' %}">Create Rate</a><br>
<div class="row col-12">
    <div class="col-lg-3 col-sm-12">
    {% load crispy_forms_tags %}
    <form method="get">
        {{ filter.form|crispy }}
        <button type="submit" class="btn btn-dark">Search rates</button>
    </form><br>
    </div>
    <div class="col-lg-9 col-sm-12">
        <table class="table table-striped">
            <caption>Rates</caption>
            <tr>
                <th scope="col">#</th>
                <th scope="col">ID</th>
                <th scope="col">Buy</th>
                <th scope="col">Sale</th>
                <th scope="col">Currency</th>
                <th scope="col">Source</th>
                {% if request.user.is_authenticated %}
                <th scope="col">Details link</th>
                {% endif %}
                {% if request.user.is_superuser %}
                <th scope="col">Actions</th>
                {% endif %}
            </tr>

        {% for rate in page_obj %}
            <tr bgcolor="{% cycle '#ffffff' '#e9e9e9' %}">
                <td scope="row">{{ forloop.counter }}</td>
                <td>{{ rate.id }}</td>
                <td>{{ rate.buy }}</td>
                <td>{{ rate.sale }}</td>
                <td>{{ rate.get_currency_display }}</td>
                <td>{{ rate.source }}</td>
                {% if request.user.is_authenticated %}
                <td><a href="{% url 'currency:rate-details' rate.id %}">Rate details</a></td>
                {% endif %}
                {% if request.user.is_superuser %}
                 <td>
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown"
                                    aria-expanded="false">
                                Actions
                            </button>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="{% url 'currency:rate-update' rate.id %}">Update</a>
                                <a class="dropdown-item" href="{% url 'currency:rate-delete' rate.id %}">Delete</a>
                            </div>
                        </div>
                 </td>
                {% endif %}
            </tr>
        {% endfor %}
        </table>
    </div>
</div>

{% include 'includes/pagination.html' %}

{% endblock content %}

app/currency/templates/list_sources.html
{% extends 'base.html' %}

{% block title %}
    Sources
{% endblock title %}

{% block content %}
    <a href="{% url 'currency:source-create' %}">Create Source</a><br>
    <form method="get">
        {{ filter.form.as_table }}
        <button type="submit" class="btn btn-dark">Search</button>
    </form><br>
    <div class="row col-12">
        <table class="table table-striped">
            <caption>Sources</caption>
            <tr bgcolor="#a0a0a0">
                <th>ID</th>
                <th>Source URL</th>
                <th>Name</th>
                <th>Logo</th>
                <th>Details link</th>
                <th>Actions</th>
            </tr>
        {% for source in page_obj %}
            <tr bgcolor="{% cycle '#ffffff' '#e9e9e9' %}">
                <td>{{ source.id }}</td>
                <td>{{ source.source_url }}</td>
                <td>{{ source.name }}</td>
                 <td><img src="{{ source.source_logo_url }}" width="50" height="50"></td>
                <td><a href="{% url 'currency:source-details' source.id %}">Source details</a></td>
                <td>
                    <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle"
                                type="button"
                                data-toggle="dropdown"
                                aria-expanded="false">Actions</button>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'currency:source-update' source.id %}">Update</a>
                            <a class="dropdown-item" href="{% url 'currency:source-delete' source.id %}">Delete</a>
                        </div>
                    </div>
                </td>
            </tr>
        {% endfor %}
        </table>
    </div>

    {% include 'includes/pagination.html' %}

{% endblock content %}

app/currency/templates/message_create.html
{% extends 'base.html' %}

{% block title %}
    Create Message
{% endblock title %}

{% block content %}
    Create Message Form
    <div class="col-lg-6 col-sm-12">
        {% load crispy_forms_tags %}
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit">Submit</button>
        </form>
    </div>
{% endblock content %}

app/currency/templates/message_delete.html
{% extends 'base.html' %}

{% block title %}
    Delete Message
{% endblock title %}

{% block content %}
    Do You really want to delete Message with id={{ contactus.id }}?
    <form method="post">
        {% csrf_token %}
        <button type="submit">Yes</button>
    </form>
{% endblock content %}

app/currency/templates/rate_create.html
{% extends 'base.html' %}

{% block title %}
    Create Rate
{% endblock title %}

{% block content %}
    Create Rate Form
    {% load crispy_forms_tags %}
    <div class="col-lg-6 col-sm-12">
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit">Submit</button>
        </form>
    </div>
{% endblock content %}

app/currency/templates/rate_delete.html
{% extends 'base.html' %}

{% block title %}
    Delete Rate
{% endblock title %}

{% block content %}
    Do You really want to delete Rate with id={{ rate.id }}?
    <form method="post">
        {% csrf_token %}
        <button type="submit">Yes</button>
    </form>
{% endblock content %}

app/currency/templates/rate_details.html
{% extends 'base.html' %}

{% block title %}
    Rate details
{% endblock title %}

{% block content %}
    <table class="table">
        <caption>Rate ({{rate.id}}) details</caption>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Buy</th>
            <th scope="col">Sell</th>
            <th scope="col">Currency</th>
            <th scope="col">Source</th>
            <th scope="col">Created</th>
        </tr>
        <tr>
            <td>{{ rate.id }}</td>
            <td>{{ rate.buy }}</td>
            <td>{{ rate.sell }}</td>
            <td>{{ rate.get_currency_display }}</td>
            <td>{{ rate.source }}</td>
            <td>{{ rate.created }}</td>
        </tr>
    </table>
{% endblock content %}

app/currency/templates/rate_update.html
{% extends 'base.html' %}

{% block title %}
    Update Rate
{% endblock title %}

{% block content %}
    Update Rate Form
    {% load crispy_forms_tags %}
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Submit</button>
    </form>
{% endblock content %}

app/currency/templates/source_create.html
{% extends 'base.html' %}

{% block title %}
    Create Source
{% endblock title %}

{% block content %}
    Create Source Form
    <div class="col-lg-6 col-sm-12">
        {% load crispy_forms_tags %}
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit">Submit</button>
        </form>
    </div>
{% endblock content %}

app/currency/templates/source_delete.html
{% extends 'base.html' %}

{% block title %}
    Delete Source
{% endblock title %}

{% block content %}
    Do You really want to delete Source with id={{ source.id }}?
    <form method="post">
        {% csrf_token %}
        <button type="submit">Yes</button>
    </form>
{% endblock content %}

app/currency/templates/source_details.html
{% extends 'base.html' %}

{% block title %}
    Source details
{% endblock title %}

{% block content %}
    <table class="table">
        <caption>Source ({{source.id}}) details</caption>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Source URL</th>
            <th scope="col">Name</th>
            <th scope="col">Note</th>
        </tr>
        <tr>
            <td>{{source.id}}</td>
            <td>{{source.source_url}}</td>
            <td>{{source.name}}</td>
            <td>{{source.note}}</td>
        </tr>
    </table>
{% endblock content %}

app/currency/templates/source_update.html
{% extends 'base.html' %}

{% block title %}
    Update Source
{% endblock title %}

{% block content %}
    Update Source Form
    {% load crispy_forms_tags %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Submit</button>
    </form>
{% endblock content %}